### ISSUE TITLE
Market status not updating on withdraw

### ISSUE THREAD

**Issue by Vitalsine85** [baofinance/bao-ui#11]
Market stays "active" even when all supplied funds have been withdrawn. i.e. I withdrew my ETH but the market still appears at the top.

**Comment by clabby** [comment]
Dust is left inside of the market when withdrawing, which is causing this issue.

**Comment by Vitalsine85** [comment]
How about we set the market to inactive if there is less than < .000001 supplied? Even with WBTC that would only be 4 cents.

**Comment by Vitalsine85** [comment]
No longer an issue with the new market list layout.
