### ISSUE TITLE
Borrow/Repay modal doesn't show wallet balance

### ISSUE THREAD

**Issue by Vitalsine85** [baofinance/bao-ui#15]
Borrow/Repay Modal does not show wallet balance anywhere. Wallet balance is only shown under Supply Stats in accordion and is not very intuitive. Additionally, the max button refers to a user's borrowed amount, but it does not take into account how much the user actually has in their wallet.

**Comment by clabby** [comment]
Added in b1ceebd4f1087ad8aea4be316ad7af0eabb88886
