### ISSUE TITLE
Cold-start/Locked Metamask Connect often fails

### ISSUE THREAD

**Issue by jondwillis** [baofinance/bao-ui#21]
Steps to reproduce:

1. Cold-start open Braze
2. Metamask is locked and/or unconnected
3. Press "Connect Wallet to Enter App" button, and "Connect" on the wallet select popup
4. Metamask Is _usually_ not opened and the UI is left in a "Connecting" state
<img width="603" alt="image" src="https://user-images.githubusercontent.com/906671/150645576-db99e3c8-68d0-424e-80d5-aff6d0723e5f.png">

There are related and intermittent issues when Metamask is in the following states:
- Connect to another network (such as Polygon)
- Has queued unlock/connect requests (can be reproduced by attempting to connect and then refreshing the page before completing)

**Comment by Vitalsine85** [comment]
I'm not able to reproduce this issue. I assumed you meant Brave and not 'Braze'? Could you test with the newest staging deployment on ropsten.app.bao.finance? If it persists, re-open the issue, but I am not having any issues in multiple browsers.
