### ISSUE TITLE
Net APY/APR incorrect

### ISSUE THREAD

**Issue by Vitalsine85** [baofinance/bao-ui#29]
Have to redo the math on this.
![image](https://user-images.githubusercontent.com/34991917/151623732-809e5a97-4382-4b6e-bb9b-f03fb1e54e5b.png)

**Comment by Vitalsine85** [comment]
Swapped netApy for borrowApy since we don't have to take into account supplyApy. Values are still slightly off. Could use another set of eyes on the calcluation. src/hooks/hard-synths/useAccountLiquidity lines 84-91

**Comment by clabby** [comment]
Fixed
