### ISSUE TITLE
MetaMask + Sign Out button does not work

### ISSUE THREAD

**Issue by jondwillis** [baofinance/bao-ui#32]
Steps to reproduce (on 1a7c94155174ad09ddd4041c47f01f9ccc454b8d):

1. Successfully connect Metamask
2. Tap `AccountButton`
3. Tap "Sign Out"
4. Account is still shown

**Comment by Vitalsine85** [comment]
Found a reference on stackOverflow about this. Seems like it has to do with MetaMask having the site marked as connected, not sure if there is a way to change that from within the frontend. I will have to read more into it. I think we might just have to deal with the issue until we stop using useWallet.

https://stackoverflow.com/questions/67856902/how-to-logout-of-metamask-account-using-web3-js#:~:text=The%20user%20can%20disconnect%20MetaMask,or%20reload%20automatically%20disconnects%20MetaMask.
